package main

import (
	"os"
	"re-mem/re_mem"
)

type User struct {
	Name    string
	Age     int
	Company string
}

const testJson = `{
  "value": [
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2949,
      "Name": "Alaska",
      "Abbreviation": "AK",
      "ActiveFlag": true,
      "Description": "Alaska",
      "StateType": "state",
      "StateCode": "AK",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-AK"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2950,
      "Name": "Alabama",
      "Abbreviation": "AL",
      "ActiveFlag": true,
      "Description": "Alabama",
      "StateType": "state",
      "StateCode": "AL",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-AL"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2951,
      "Name": "Arkansas",
      "Abbreviation": "AR",
      "ActiveFlag": true,
      "Description": "Arkansas",
      "StateType": "state",
      "StateCode": "AR",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-AR"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2952,
      "Name": "American Samoa (see also separate entry under AS)",
      "Abbreviation": "AS",
      "ActiveFlag": true,
      "Description": "American Samoa (see also separate entry under AS)",
      "StateType": "outlying area",
      "StateCode": "AS",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-AS"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2953,
      "Name": "Arizona",
      "Abbreviation": "AZ",
      "ActiveFlag": true,
      "Description": "Arizona",
      "StateType": "state",
      "StateCode": "AZ",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-AZ"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2954,
      "Name": "California",
      "Abbreviation": "CA",
      "ActiveFlag": true,
      "Description": "California",
      "StateType": "state",
      "StateCode": "CA",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-CA"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2955,
      "Name": "Colorado",
      "Abbreviation": "CO",
      "ActiveFlag": true,
      "Description": "Colorado",
      "StateType": "state",
      "StateCode": "CO",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-CO"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2956,
      "Name": "Connecticut",
      "Abbreviation": "CT",
      "ActiveFlag": true,
      "Description": "Connecticut",
      "StateType": "state",
      "StateCode": "CT",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-CT"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2957,
      "Name": "District of Columbia",
      "Abbreviation": "DC",
      "ActiveFlag": true,
      "Description": "District of Columbia",
      "StateType": "district",
      "StateCode": "DC",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-DC"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2958,
      "Name": "Delaware",
      "Abbreviation": "DE",
      "ActiveFlag": true,
      "Description": "Delaware",
      "StateType": "state",
      "StateCode": "DE",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-DE"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2959,
      "Name": "Florida",
      "Abbreviation": "FL",
      "ActiveFlag": true,
      "Description": "Florida",
      "StateType": "state",
      "StateCode": "FL",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-FL"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2960,
      "Name": "Georgia",
      "Abbreviation": "GA",
      "ActiveFlag": true,
      "Description": "Georgia",
      "StateType": "state",
      "StateCode": "GA",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-GA"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2961,
      "Name": "Guam (see also separate entry under GU)",
      "Abbreviation": "GU",
      "ActiveFlag": true,
      "Description": "Guam (see also separate entry under GU)",
      "StateType": "outlying area",
      "StateCode": "GU",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-GU"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2962,
      "Name": "Hawaii",
      "Abbreviation": "HI",
      "ActiveFlag": true,
      "Description": "Hawaii",
      "StateType": "state",
      "StateCode": "HI",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-HI"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2963,
      "Name": "Iowa",
      "Abbreviation": "IA",
      "ActiveFlag": true,
      "Description": "Iowa",
      "StateType": "state",
      "StateCode": "IA",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-IA"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2964,
      "Name": "Idaho",
      "Abbreviation": "ID",
      "ActiveFlag": true,
      "Description": "Idaho",
      "StateType": "state",
      "StateCode": "ID",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-ID"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2965,
      "Name": "Illinois",
      "Abbreviation": "IL",
      "ActiveFlag": true,
      "Description": "Illinois",
      "StateType": "state",
      "StateCode": "IL",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-IL"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2966,
      "Name": "Indiana",
      "Abbreviation": "IN",
      "ActiveFlag": true,
      "Description": "Indiana",
      "StateType": "state",
      "StateCode": "IN",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-IN"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2967,
      "Name": "Kansas",
      "Abbreviation": "KS",
      "ActiveFlag": true,
      "Description": "Kansas",
      "StateType": "state",
      "StateCode": "KS",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-KS"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2968,
      "Name": "Kentucky",
      "Abbreviation": "KY",
      "ActiveFlag": true,
      "Description": "Kentucky",
      "StateType": "state",
      "StateCode": "KY",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-KY"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2969,
      "Name": "Louisiana",
      "Abbreviation": "LA",
      "ActiveFlag": true,
      "Description": "Louisiana",
      "StateType": "state",
      "StateCode": "LA",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-LA"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2970,
      "Name": "Massachusetts",
      "Abbreviation": "MA",
      "ActiveFlag": true,
      "Description": "Massachusetts",
      "StateType": "state",
      "StateCode": "MA",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-MA"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2971,
      "Name": "Maryland",
      "Abbreviation": "MD",
      "ActiveFlag": true,
      "Description": "Maryland",
      "StateType": "state",
      "StateCode": "MD",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-MD"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2972,
      "Name": "Maine",
      "Abbreviation": "ME",
      "ActiveFlag": true,
      "Description": "Maine",
      "StateType": "state",
      "StateCode": "ME",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-ME"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2973,
      "Name": "Michigan",
      "Abbreviation": "MI",
      "ActiveFlag": true,
      "Description": "Michigan",
      "StateType": "state",
      "StateCode": "MI",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-MI"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2974,
      "Name": "Minnesota",
      "Abbreviation": "MN",
      "ActiveFlag": true,
      "Description": "Minnesota",
      "StateType": "state",
      "StateCode": "MN",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-MN"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2975,
      "Name": "Missouri",
      "Abbreviation": "MO",
      "ActiveFlag": true,
      "Description": "Missouri",
      "StateType": "state",
      "StateCode": "MO",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-MO"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2976,
      "Name": "Northern Mariana Islands (see also separate entry under MP)",
      "Abbreviation": "MP",
      "ActiveFlag": true,
      "Description": "Northern Mariana Islands (see also separate entry under MP)",
      "StateType": "outlying area",
      "StateCode": "MP",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-MP"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2977,
      "Name": "Mississippi",
      "Abbreviation": "MS",
      "ActiveFlag": true,
      "Description": "Mississippi",
      "StateType": "state",
      "StateCode": "MS",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-MS"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2978,
      "Name": "Montana",
      "Abbreviation": "MT",
      "ActiveFlag": true,
      "Description": "Montana",
      "StateType": "state",
      "StateCode": "MT",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-MT"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2979,
      "Name": "North Carolina",
      "Abbreviation": "NC",
      "ActiveFlag": true,
      "Description": "North Carolina",
      "StateType": "state",
      "StateCode": "NC",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-NC"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2980,
      "Name": "North Dakota",
      "Abbreviation": "ND",
      "ActiveFlag": true,
      "Description": "North Dakota",
      "StateType": "state",
      "StateCode": "ND",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-ND"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2981,
      "Name": "Nebraska",
      "Abbreviation": "NE",
      "ActiveFlag": true,
      "Description": "Nebraska",
      "StateType": "state",
      "StateCode": "NE",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-NE"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2982,
      "Name": "New Hampshire",
      "Abbreviation": "NH",
      "ActiveFlag": true,
      "Description": "New Hampshire",
      "StateType": "state",
      "StateCode": "NH",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-NH"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2983,
      "Name": "New Jersey",
      "Abbreviation": "NJ",
      "ActiveFlag": true,
      "Description": "New Jersey",
      "StateType": "state",
      "StateCode": "NJ",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-NJ"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2984,
      "Name": "New Mexico",
      "Abbreviation": "NM",
      "ActiveFlag": true,
      "Description": "New Mexico",
      "StateType": "state",
      "StateCode": "NM",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-NM"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2985,
      "Name": "Nevada",
      "Abbreviation": "NV",
      "ActiveFlag": true,
      "Description": "Nevada",
      "StateType": "state",
      "StateCode": "NV",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-NV"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2986,
      "Name": "New York",
      "Abbreviation": "NY",
      "ActiveFlag": true,
      "Description": "New York",
      "StateType": "state",
      "StateCode": "NY",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-NY"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2987,
      "Name": "Ohio",
      "Abbreviation": "OH",
      "ActiveFlag": true,
      "Description": "Ohio",
      "StateType": "state",
      "StateCode": "OH",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-OH"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2988,
      "Name": "Oklahoma",
      "Abbreviation": "OK",
      "ActiveFlag": true,
      "Description": "Oklahoma",
      "StateType": "state",
      "StateCode": "OK",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-OK"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2989,
      "Name": "Oregon",
      "Abbreviation": "OR",
      "ActiveFlag": true,
      "Description": "Oregon",
      "StateType": "state",
      "StateCode": "OR",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-OR"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2990,
      "Name": "Pennsylvania",
      "Abbreviation": "PA",
      "ActiveFlag": true,
      "Description": "Pennsylvania",
      "StateType": "state",
      "StateCode": "PA",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-PA"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2991,
      "Name": "Puerto Rico (see also separate entry under PR)",
      "Abbreviation": "PR",
      "ActiveFlag": true,
      "Description": "Puerto Rico (see also separate entry under PR)",
      "StateType": "outlying area",
      "StateCode": "PR",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-PR"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2992,
      "Name": "Rhode Island",
      "Abbreviation": "RI",
      "ActiveFlag": true,
      "Description": "Rhode Island",
      "StateType": "state",
      "StateCode": "RI",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-RI"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2993,
      "Name": "South Carolina",
      "Abbreviation": "SC",
      "ActiveFlag": true,
      "Description": "South Carolina",
      "StateType": "state",
      "StateCode": "SC",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-SC"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2994,
      "Name": "South Dakota",
      "Abbreviation": "SD",
      "ActiveFlag": true,
      "Description": "South Dakota",
      "StateType": "state",
      "StateCode": "SD",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-SD"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2995,
      "Name": "Tennessee",
      "Abbreviation": "TN",
      "ActiveFlag": true,
      "Description": "Tennessee",
      "StateType": "state",
      "StateCode": "TN",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-TN"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2996,
      "Name": "Texas",
      "Abbreviation": "TX",
      "ActiveFlag": true,
      "Description": "Texas",
      "StateType": "state",
      "StateCode": "TX",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-TX"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2997,
      "Name": "United States Minor Outlying Islands (see also separate entry under UM)",
      "Abbreviation": "UM",
      "ActiveFlag": true,
      "Description": "United States Minor Outlying Islands (see also separate entry under UM)",
      "StateType": "outlying area",
      "StateCode": "UM",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-UM"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2998,
      "Name": "Utah",
      "Abbreviation": "UT",
      "ActiveFlag": true,
      "Description": "Utah",
      "StateType": "state",
      "StateCode": "UT",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-UT"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 2999,
      "Name": "Virginia",
      "Abbreviation": "VA",
      "ActiveFlag": true,
      "Description": "Virginia",
      "StateType": "state",
      "StateCode": "VA",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-VA"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 3000,
      "Name": "Virgin Islands, U.S. (see also separate entry under VI)",
      "Abbreviation": "VI",
      "ActiveFlag": true,
      "Description": "Virgin Islands, U.S. (see also separate entry under VI)",
      "StateType": "outlying area",
      "StateCode": "VI",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-VI"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 3001,
      "Name": "Vermont",
      "Abbreviation": "VT",
      "ActiveFlag": true,
      "Description": "Vermont",
      "StateType": "state",
      "StateCode": "VT",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-VT"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 3002,
      "Name": "Washington",
      "Abbreviation": "WA",
      "ActiveFlag": true,
      "Description": "Washington",
      "StateType": "state",
      "StateCode": "WA",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-WA"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 3003,
      "Name": "Wisconsin",
      "Abbreviation": "WI",
      "ActiveFlag": true,
      "Description": "Wisconsin",
      "StateType": "state",
      "StateCode": "WI",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-WI"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 3004,
      "Name": "West Virginia",
      "Abbreviation": "WV",
      "ActiveFlag": true,
      "Description": "West Virginia",
      "StateType": "state",
      "StateCode": "WV",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-WV"
    },
    {
      "CountryId": 230,
      "CountryName": "United States",
      "Id": 3005,
      "Name": "Wyoming",
      "Abbreviation": "WY",
      "ActiveFlag": true,
      "Description": "Wyoming",
      "StateType": "state",
      "StateCode": "WY",
      "UpdateDate": "2011-10-11T00:29:28.347Z",
      "UpdatedByName": "zAdmin2",
      "TabOrder": 0,
      "Default": false,
      "CoStAbbr": "US-WY"
    }
  ]
}`

func main() {
	store := re_mem.NewLocalStorage("/Users/samorozco/first_db")
	wos, err := store.GetCollection("workorders")
	if err != nil {
		println("failed to get collection")
		os.Exit(1)
	}

	wo, err := wos.Get("f34c8f1f-5806-4b8d-a8de-c3e25a112377")
	println(wo.String())

	docs, err := wos.Query("CountryId", "230")
	if err != nil {
		panic(err)
	}

	for _, v := range docs {
		println(v.String())
	}

	//data := make(map[string]interface{}, 0)
	//err = json.Unmarshal([]byte(testJson), &data)
	//if err != nil {
	//	panic(err)
	//}
	//values := data["value"]
	//slices := values.([]interface{})
	//for _, value := range slices {
	//	key, err := wos.Create(value)
	//	if err != nil {
	//		panic(err)
	//	}
	//	println(key)
	//}

	//names := []string{"sam", "madison", "steven", "april", "sawyer"}
	//ages := []int{50, 55, 34, 231, 121, 12, 77}
	//company := []string{"apple", "microsoft", "amazon", "dropbox", "this"}
	//
	//for i := 0; i < 100; i++ {
	//	key, err := col.Create(&User{
	//		Name:    names[rand.Int()%len(names)],
	//		Age:     ages[rand.Int()%len(ages)],
	//		Company: company[rand.Int()%len(company)],
	//	})
	//
	//	if err != nil {
	//		panic(err)
	//	}
	//	println(key)
	//}
}
